CREATE TABLE `Account` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`accountId` text NOT NULL,
	`providerId` text NOT NULL,
	`accessToken` text,
	`refreshToken` text,
	`accessTokenExpiresAt` integer,
	`refreshTokenExpiresAt` integer,
	`scope` text,
	`idToken` text,
	`password` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_account_userId` ON `Account` (`userId`);--> statement-breakpoint
CREATE TABLE `DashboardPreferences` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`layout` text DEFAULT '{"widgets":[]}' NOT NULL,
	`widgets` text DEFAULT '[]' NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `DashboardPreferences_userId_unique` ON `DashboardPreferences` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_dashboardPreferences_userId` ON `DashboardPreferences` (`userId`);--> statement-breakpoint
CREATE TABLE `Session` (
	`id` text PRIMARY KEY NOT NULL,
	`token` text NOT NULL,
	`userId` text NOT NULL,
	`expiresAt` integer NOT NULL,
	`ipAddress` text,
	`userAgent` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `Session_token_unique` ON `Session` (`token`);--> statement-breakpoint
CREATE INDEX `idx_session_userId` ON `Session` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_session_expiresAt` ON `Session` (`expiresAt`);--> statement-breakpoint
CREATE TABLE `User` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`name` text,
	`image` text,
	`passwordHash` text,
	`personId` text,
	`role` text DEFAULT 'VIEWER' NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`mustChangePassword` integer DEFAULT false NOT NULL,
	`preferredLanguage` text DEFAULT 'en',
	`oidcProvider` text,
	`oidcSubject` text,
	`emailVerified` integer DEFAULT false NOT NULL,
	`profileClaimStatus` text DEFAULT 'PENDING' NOT NULL,
	`profileClaimedAt` integer,
	`invitedById` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	`lastLoginAt` integer,
	`failedLoginAttempts` integer DEFAULT 0 NOT NULL,
	`lockedUntil` integer,
	`lastFailedLoginAt` integer,
	`emailNotificationPreferences` text DEFAULT '{"newMemberJoined":true,"birthdayReminders":true,"suggestionsCreated":true,"suggestionsUpdated":true}'
);
--> statement-breakpoint
CREATE UNIQUE INDEX `User_email_unique` ON `User` (`email`);--> statement-breakpoint
CREATE UNIQUE INDEX `User_personId_unique` ON `User` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_user_email` ON `User` (`email`);--> statement-breakpoint
CREATE INDEX `idx_user_personId` ON `User` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_user_oidcProvider` ON `User` (`oidcProvider`);--> statement-breakpoint
CREATE TABLE `Verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expiresAt` integer NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_verification_identifier` ON `Verification` (`identifier`);--> statement-breakpoint
CREATE TABLE `Person` (
	`id` text PRIMARY KEY NOT NULL,
	`firstName` text NOT NULL,
	`lastName` text NOT NULL,
	`maidenName` text,
	`dateOfBirth` text,
	`dateOfPassing` text,
	`birthPlace` text,
	`nativePlace` text,
	`gender` text,
	`photoUrl` text,
	`bio` text,
	`email` text,
	`phone` text,
	`currentAddress` text,
	`workAddress` text,
	`profession` text,
	`employer` text,
	`socialLinks` text,
	`isLiving` integer DEFAULT true NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	`createdById` text,
	`deletedAt` integer
);
--> statement-breakpoint
CREATE INDEX `idx_person_lastName_firstName` ON `Person` (`lastName`,`firstName`);--> statement-breakpoint
CREATE INDEX `idx_person_createdById` ON `Person` (`createdById`);--> statement-breakpoint
CREATE INDEX `idx_person_dateOfBirth` ON `Person` (`dateOfBirth`);--> statement-breakpoint
CREATE INDEX `idx_person_isLiving` ON `Person` (`isLiving`);--> statement-breakpoint
CREATE INDEX `idx_person_deletedAt` ON `Person` (`deletedAt`);--> statement-breakpoint
CREATE TABLE `Relationship` (
	`id` text PRIMARY KEY NOT NULL,
	`personId` text NOT NULL,
	`relatedPersonId` text NOT NULL,
	`type` text NOT NULL,
	`marriageDate` text,
	`divorceDate` text,
	`isActive` integer DEFAULT true NOT NULL,
	`isAutoGenerated` integer DEFAULT false NOT NULL,
	`sourceRelationshipId` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_relationship_personId` ON `Relationship` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_relationship_relatedPersonId` ON `Relationship` (`relatedPersonId`);--> statement-breakpoint
CREATE INDEX `idx_relationship_personId_type` ON `Relationship` (`personId`,`type`);--> statement-breakpoint
CREATE INDEX `idx_relationship_relatedPersonId_type` ON `Relationship` (`relatedPersonId`,`type`);--> statement-breakpoint
CREATE INDEX `idx_relationship_sourceRelationshipId` ON `Relationship` (`sourceRelationshipId`);--> statement-breakpoint
CREATE INDEX `idx_relationship_isAutoGenerated` ON `Relationship` (`isAutoGenerated`);--> statement-breakpoint
CREATE TABLE `CalendarToken` (
	`id` text PRIMARY KEY NOT NULL,
	`token` text NOT NULL,
	`userId` text NOT NULL,
	`name` text,
	`expiresAt` integer NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`lastUsedAt` integer,
	`rotationPolicy` text DEFAULT 'annual' NOT NULL,
	`rotatedAt` integer,
	`rotatedFrom` text,
	`scopes` text DEFAULT '["calendar:read"]',
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `CalendarToken_token_unique` ON `CalendarToken` (`token`);--> statement-breakpoint
CREATE INDEX `idx_calendarToken_userId` ON `CalendarToken` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_calendarToken_token` ON `CalendarToken` (`token`);--> statement-breakpoint
CREATE INDEX `idx_calendarToken_expiresAt` ON `CalendarToken` (`expiresAt`);--> statement-breakpoint
CREATE INDEX `idx_calendarToken_isActive` ON `CalendarToken` (`isActive`);--> statement-breakpoint
CREATE INDEX `idx_calendarToken_userId_isActive` ON `CalendarToken` (`userId`,`isActive`);--> statement-breakpoint
CREATE TABLE `OAuthState` (
	`id` text PRIMARY KEY NOT NULL,
	`state` text NOT NULL,
	`codeVerifier` text NOT NULL,
	`provider` text NOT NULL,
	`redirectTo` text,
	`expiresAt` integer NOT NULL,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `OAuthState_state_unique` ON `OAuthState` (`state`);--> statement-breakpoint
CREATE INDEX `idx_oAuthState_state` ON `OAuthState` (`state`);--> statement-breakpoint
CREATE INDEX `idx_oAuthState_expiresAt` ON `OAuthState` (`expiresAt`);--> statement-breakpoint
CREATE TABLE `EventMedia` (
	`id` text PRIMARY KEY NOT NULL,
	`mediaId` text NOT NULL,
	`personId` text NOT NULL,
	`eventType` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_eventMedia_mediaId` ON `EventMedia` (`mediaId`);--> statement-breakpoint
CREATE INDEX `idx_eventMedia_personId` ON `EventMedia` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_eventMedia_eventType` ON `EventMedia` (`eventType`);--> statement-breakpoint
CREATE TABLE `EventParticipant` (
	`id` text PRIMARY KEY NOT NULL,
	`eventId` text NOT NULL,
	`personId` text NOT NULL,
	`role` text,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_eventParticipant_eventId` ON `EventParticipant` (`eventId`);--> statement-breakpoint
CREATE INDEX `idx_eventParticipant_personId` ON `EventParticipant` (`personId`);--> statement-breakpoint
CREATE TABLE `EventSource` (
	`id` text PRIMARY KEY NOT NULL,
	`sourceId` text NOT NULL,
	`personId` text NOT NULL,
	`eventType` text NOT NULL,
	`confidence` text,
	`sourceNotes` text
);
--> statement-breakpoint
CREATE INDEX `idx_eventSource_sourceId` ON `EventSource` (`sourceId`);--> statement-breakpoint
CREATE INDEX `idx_eventSource_personId` ON `EventSource` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_eventSource_eventType` ON `EventSource` (`eventType`);--> statement-breakpoint
CREATE TABLE `Event` (
	`id` text PRIMARY KEY NOT NULL,
	`personId` text NOT NULL,
	`type` text NOT NULL,
	`date` text,
	`place` text,
	`placeId` text,
	`description` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_event_personId` ON `Event` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_event_type` ON `Event` (`type`);--> statement-breakpoint
CREATE INDEX `idx_event_date` ON `Event` (`date`);--> statement-breakpoint
CREATE INDEX `idx_event_placeId` ON `Event` (`placeId`);--> statement-breakpoint
CREATE TABLE `PlacePersonLink` (
	`id` text PRIMARY KEY NOT NULL,
	`personId` text NOT NULL,
	`placeId` text NOT NULL,
	`fromYear` integer,
	`toYear` integer,
	`type` text,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_placePersonLink_personId` ON `PlacePersonLink` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_placePersonLink_placeId` ON `PlacePersonLink` (`placeId`);--> statement-breakpoint
CREATE TABLE `Place` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`placeType` text NOT NULL,
	`latitude` real,
	`longitude` real,
	`parentId` text,
	`description` text,
	`alternativeNames` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_place_name` ON `Place` (`name`);--> statement-breakpoint
CREATE INDEX `idx_place_placeType` ON `Place` (`placeType`);--> statement-breakpoint
CREATE INDEX `idx_place_parentId` ON `Place` (`parentId`);--> statement-breakpoint
CREATE INDEX `idx_place_latitude_longitude` ON `Place` (`latitude`,`longitude`);--> statement-breakpoint
CREATE TABLE `MediaObject` (
	`id` text PRIMARY KEY NOT NULL,
	`filePath` text NOT NULL,
	`format` text NOT NULL,
	`mimeType` text NOT NULL,
	`fileSize` integer NOT NULL,
	`title` text,
	`description` text,
	`source` text,
	`width` integer,
	`height` integer,
	`thumbnailPath` text,
	`webpPath` text,
	`thumb400Path` text,
	`thumb800Path` text,
	`thumb1200Path` text,
	`uploadedAt` integer NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_mediaObject_filePath` ON `MediaObject` (`filePath`);--> statement-breakpoint
CREATE INDEX `idx_mediaObject_uploadedAt` ON `MediaObject` (`uploadedAt`);--> statement-breakpoint
CREATE TABLE `PersonMedia` (
	`id` text PRIMARY KEY NOT NULL,
	`personId` text NOT NULL,
	`mediaId` text NOT NULL,
	`isPrimary` integer DEFAULT false NOT NULL,
	`caption` text,
	`displayOrder` integer NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_personMedia_personId` ON `PersonMedia` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_personMedia_mediaId` ON `PersonMedia` (`mediaId`);--> statement-breakpoint
CREATE INDEX `idx_personMedia_isPrimary` ON `PersonMedia` (`isPrimary`);--> statement-breakpoint
CREATE TABLE `BackupSettings` (
	`id` text PRIMARY KEY NOT NULL,
	`dailyEnabled` integer DEFAULT true NOT NULL,
	`dailyTime` text DEFAULT '02:00' NOT NULL,
	`weeklyEnabled` integer DEFAULT true NOT NULL,
	`weeklyDay` integer DEFAULT 0 NOT NULL,
	`weeklyTime` text DEFAULT '03:00' NOT NULL,
	`monthlyEnabled` integer DEFAULT true NOT NULL,
	`monthlyDay` integer DEFAULT 1 NOT NULL,
	`monthlyTime` text DEFAULT '04:00' NOT NULL,
	`dailyRetention` integer DEFAULT 7 NOT NULL,
	`weeklyRetention` integer DEFAULT 4 NOT NULL,
	`monthlyRetention` integer DEFAULT 12 NOT NULL,
	`storageProvider` text DEFAULT 'LOCAL' NOT NULL,
	`storageBucket` text,
	`storageRegion` text,
	`storagePath` text DEFAULT 'backups' NOT NULL,
	`includePhotos` integer DEFAULT true NOT NULL,
	`includeAuditLogs` integer DEFAULT false NOT NULL,
	`compressLevel` integer DEFAULT 6 NOT NULL,
	`notifyOnSuccess` integer DEFAULT false NOT NULL,
	`notifyOnFailure` integer DEFAULT true NOT NULL,
	`notificationEmails` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `Backup` (
	`id` text PRIMARY KEY NOT NULL,
	`filename` text NOT NULL,
	`type` text NOT NULL,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`size` integer,
	`location` text DEFAULT 'LOCAL' NOT NULL,
	`personCount` integer,
	`relationshipCount` integer,
	`eventCount` integer,
	`mediaCount` integer,
	`duration` integer,
	`error` text,
	`createdAt` integer NOT NULL,
	`deletedAt` integer
);
--> statement-breakpoint
CREATE INDEX `idx_backup_type_createdAt` ON `Backup` (`type`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_backup_status` ON `Backup` (`status`);--> statement-breakpoint
CREATE INDEX `idx_backup_createdAt` ON `Backup` (`createdAt`);--> statement-breakpoint
CREATE TABLE `AuditLog` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`action` text NOT NULL,
	`entityType` text NOT NULL,
	`entityId` text,
	`previousData` text,
	`newData` text,
	`ipAddress` text,
	`userAgent` text,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_auditLog_userId` ON `AuditLog` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_auditLog_entityType_entityId` ON `AuditLog` (`entityType`,`entityId`);--> statement-breakpoint
CREATE INDEX `idx_auditLog_createdAt` ON `AuditLog` (`createdAt`);--> statement-breakpoint
CREATE TABLE `EmailLog` (
	`id` text PRIMARY KEY NOT NULL,
	`recipientEmail` text NOT NULL,
	`subject` text NOT NULL,
	`emailType` text NOT NULL,
	`status` text DEFAULT 'sent' NOT NULL,
	`sentAt` integer NOT NULL,
	`error` text,
	`resendId` text,
	`metadata` text,
	`createdById` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_emailLog_recipientEmail` ON `EmailLog` (`recipientEmail`);--> statement-breakpoint
CREATE INDEX `idx_emailLog_emailType` ON `EmailLog` (`emailType`);--> statement-breakpoint
CREATE INDEX `idx_emailLog_status` ON `EmailLog` (`status`);--> statement-breakpoint
CREATE INDEX `idx_emailLog_sentAt` ON `EmailLog` (`sentAt`);--> statement-breakpoint
CREATE TABLE `FamilySettings` (
	`id` text PRIMARY KEY NOT NULL,
	`familyName` text DEFAULT 'Our Family' NOT NULL,
	`description` text,
	`locale` text DEFAULT 'en' NOT NULL,
	`customLabels` text,
	`defaultPrivacy` text DEFAULT 'MEMBERS_ONLY' NOT NULL,
	`allowSelfRegistration` integer DEFAULT true NOT NULL,
	`requireApprovalForEdits` integer DEFAULT true NOT NULL,
	`metricsDashboardUrl` text,
	`metricsApiUrl` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `Invite` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`personId` text,
	`role` text DEFAULT 'MEMBER' NOT NULL,
	`invitedById` text NOT NULL,
	`token` text NOT NULL,
	`expiresAt` integer NOT NULL,
	`acceptedAt` integer,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `Invite_token_unique` ON `Invite` (`token`);--> statement-breakpoint
CREATE INDEX `idx_invite_email` ON `Invite` (`email`);--> statement-breakpoint
CREATE INDEX `idx_invite_invitedById` ON `Invite` (`invitedById`);--> statement-breakpoint
CREATE INDEX `idx_invite_status` ON `Invite` (`status`);--> statement-breakpoint
CREATE TABLE `ResearchNote` (
	`id` text PRIMARY KEY NOT NULL,
	`sourceId` text NOT NULL,
	`personId` text NOT NULL,
	`eventType` text NOT NULL,
	`findings` text NOT NULL,
	`methodology` text,
	`limitations` text,
	`relatedSources` text,
	`conclusionReliability` text,
	`createdById` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_researchNote_sourceId` ON `ResearchNote` (`sourceId`);--> statement-breakpoint
CREATE INDEX `idx_researchNote_personId` ON `ResearchNote` (`personId`);--> statement-breakpoint
CREATE INDEX `idx_researchNote_eventType` ON `ResearchNote` (`eventType`);--> statement-breakpoint
CREATE INDEX `idx_researchNote_createdById` ON `ResearchNote` (`createdById`);--> statement-breakpoint
CREATE TABLE `Source` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`author` text,
	`publicationDate` text,
	`description` text,
	`repository` text,
	`notes` text,
	`sourceType` text,
	`citationFormat` text,
	`doi` text,
	`url` text,
	`isbn` text,
	`callNumber` text,
	`accessDate` integer,
	`confidence` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_source_title` ON `Source` (`title`);--> statement-breakpoint
CREATE INDEX `idx_source_sourceType` ON `Source` (`sourceType`);--> statement-breakpoint
CREATE INDEX `idx_source_doi` ON `Source` (`doi`);--> statement-breakpoint
CREATE TABLE `Suggestion` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`targetPersonId` text,
	`suggestedData` text NOT NULL,
	`reason` text,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`submittedById` text NOT NULL,
	`reviewedById` text,
	`reviewNote` text,
	`submittedAt` integer NOT NULL,
	`reviewedAt` integer
);
--> statement-breakpoint
CREATE INDEX `idx_suggestion_status` ON `Suggestion` (`status`);--> statement-breakpoint
CREATE INDEX `idx_suggestion_submittedById` ON `Suggestion` (`submittedById`);--> statement-breakpoint
CREATE INDEX `idx_suggestion_targetPersonId` ON `Suggestion` (`targetPersonId`);--> statement-breakpoint
CREATE TABLE `DeviceToken` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`token` text NOT NULL,
	`platform` text NOT NULL,
	`deviceId` text,
	`isActive` integer DEFAULT true NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_deviceToken_userId` ON `DeviceToken` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_deviceToken_isActive` ON `DeviceToken` (`isActive`);--> statement-breakpoint
CREATE INDEX `idx_deviceToken_userId_isActive` ON `DeviceToken` (`userId`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_deviceToken_deviceId` ON `DeviceToken` (`deviceId`);--> statement-breakpoint
CREATE TABLE `Notification` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`body` text NOT NULL,
	`data` text,
	`readAt` integer,
	`sentAt` integer,
	`createdAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_notification_userId` ON `Notification` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_notification_type` ON `Notification` (`type`);--> statement-breakpoint
CREATE INDEX `idx_notification_createdAt` ON `Notification` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_notification_userId_readAt` ON `Notification` (`userId`,`readAt`);