/**
 * Drizzle ORM Schema - Relationship
 *
 * Maps the Prisma Relationship model
 */

import {
  pgTable,
  text,
  timestamp,
  boolean,
  date,
  unique,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { relationshipTypeEnum } from "./enums";
import { persons } from "./person";

/**
 * Relationship table - person-to-person genealogical relationships
 */
export const relationships = pgTable(
  "Relationship",
  {
    id: text("id").primaryKey(),
    personId: text("personId").notNull(),
    relatedPersonId: text("relatedPersonId").notNull(),
    type: relationshipTypeEnum("type").notNull(),
    marriageDate: date("marriageDate", { mode: "date" }),
    divorceDate: date("divorceDate", { mode: "date" }),
    isActive: boolean("isActive").notNull().default(true),
    isAutoGenerated: boolean("isAutoGenerated").notNull().default(false),
    sourceRelationshipId: text("sourceRelationshipId"),
    createdAt: timestamp("createdAt", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updatedAt", { mode: "date" }).notNull(),
  },
  (table) => [
    unique().on(table.personId, table.relatedPersonId, table.type),
    index("idx_relationship_personId").on(table.personId),
    index("idx_relationship_relatedPersonId").on(table.relatedPersonId),
    index("idx_relationship_personId_type").on(table.personId, table.type),
    index("idx_relationship_relatedPersonId_type").on(
      table.relatedPersonId,
      table.type
    ),
    index("idx_relationship_sourceRelationshipId").on(
      table.sourceRelationshipId
    ),
    index("idx_relationship_isAutoGenerated").on(table.isAutoGenerated),
  ]
);

/**
 * Relationship relations
 */
export const relationshipsRelations = relations(
  relationships,
  ({ one, many }) => ({
    person: one(persons, {
      fields: [relationships.personId],
      references: [persons.id],
      relationName: "RelationshipFrom",
    }),
    relatedPerson: one(persons, {
      fields: [relationships.relatedPersonId],
      references: [persons.id],
      relationName: "RelationshipTo",
    }),
    sourceRelationship: one(relationships, {
      fields: [relationships.sourceRelationshipId],
      references: [relationships.id],
      relationName: "DerivedRelationships",
    }),
    derivedRelationships: many(relationships, {
      relationName: "DerivedRelationships",
    }),
  })
);
