/**
 * Drizzle ORM Schema - Relationship (SQLite)
 */

import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";
import { persons } from "./person";

export const relationships = sqliteTable(
  "Relationship",
  {
    id: text("id").primaryKey(),
    personId: text("personId").notNull(),
    relatedPersonId: text("relatedPersonId").notNull(),
    type: text("type").notNull(),
    marriageDate: text("marriageDate"),
    divorceDate: text("divorceDate"),
    isActive: integer("isActive", { mode: "boolean" }).notNull().default(true),
    isAutoGenerated: integer("isAutoGenerated", { mode: "boolean" })
      .notNull()
      .default(false),
    sourceRelationshipId: text("sourceRelationshipId"),
    createdAt: integer("createdAt", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).notNull(),
  },
  (table) => [
    index("idx_relationship_personId").on(table.personId),
    index("idx_relationship_relatedPersonId").on(table.relatedPersonId),
    index("idx_relationship_personId_type").on(table.personId, table.type),
    index("idx_relationship_relatedPersonId_type").on(
      table.relatedPersonId,
      table.type
    ),
    index("idx_relationship_sourceRelationshipId").on(
      table.sourceRelationshipId
    ),
    index("idx_relationship_isAutoGenerated").on(table.isAutoGenerated),
  ]
);

export const relationshipsRelations = relations(
  relationships,
  ({ one, many }) => ({
    person: one(persons, {
      fields: [relationships.personId],
      references: [persons.id],
      relationName: "RelationshipFrom",
    }),
    relatedPerson: one(persons, {
      fields: [relationships.relatedPersonId],
      references: [persons.id],
      relationName: "RelationshipTo",
    }),
    sourceRelationship: one(relationships, {
      fields: [relationships.sourceRelationshipId],
      references: [relationships.id],
      relationName: "DerivedRelationships",
    }),
    derivedRelationships: many(relationships, {
      relationName: "DerivedRelationships",
    }),
  })
);
