/**
 * CSP Nonce utility
 *
 * Extracts the Content Security Policy nonce from request headers.
 * The nonce is generated by Hono's secureHeaders middleware and passed
 * via the x-csp-nonce header.
 *
 * This allows inline scripts in the HTML to include the nonce attribute,
 * satisfying CSP requirements without using unsafe-inline.
 */

/**
 * Get the CSP nonce for the current request
 *
 * @returns The nonce string (e.g., "abc123def456") or undefined if not available
 */
export function getCspNonce(): string | undefined {
  try {
    // In TanStack Start server functions, we can access headers via getHeaders
    // This is called within the server function context where headers are available
    const { getHeaders } = require("@tanstack/react-start/server");
    const headers = getHeaders();

    // Get the nonce passed by Hono's secureHeaders middleware
    return headers?.["x-csp-nonce"];
  } catch {
    // If getHeaders is not available or fails, return undefined
    // This is normal in client-only contexts
    return undefined;
  }
}
