name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement to Vamsa!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature.
      placeholder: Add a filter to the family tree view...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature address?
      placeholder: Users cannot easily...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think this should work?
      placeholder: I propose we...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: We could also...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Mockups, screenshots, related issues...
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues and discussions
          required: true
