CREATE TYPE "public"."AuditAction" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT');--> statement-breakpoint
CREATE TYPE "public"."BackupStatus" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DELETED');--> statement-breakpoint
CREATE TYPE "public"."BackupType" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'MANUAL');--> statement-breakpoint
CREATE TYPE "public"."EventType" AS ENUM('BIRTH', 'DEATH', 'MARRIAGE', 'DIVORCE', 'BURIAL', 'GRADUATION', 'ENGAGEMENT', 'DIVORCE_FILED', 'ADOPTION', 'CONFIRMATION', 'IMMIGRATION', 'EMIGRATION', 'NATURALIZATION', 'RESIDENCE', 'CUSTOM');--> statement-breakpoint
CREATE TYPE "public"."Gender" AS ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');--> statement-breakpoint
CREATE TYPE "public"."InviteStatus" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');--> statement-breakpoint
CREATE TYPE "public"."PersonPlaceType" AS ENUM('BIRTH', 'MARRIAGE', 'DEATH', 'LIVED', 'WORKED', 'STUDIED', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."PlaceType" AS ENUM('COUNTRY', 'STATE', 'COUNTY', 'CITY', 'TOWN', 'VILLAGE', 'PARISH', 'DISTRICT', 'REGION', 'PROVINCE', 'TERRITORY', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."PrivacyLevel" AS ENUM('PUBLIC', 'MEMBERS_ONLY', 'ADMIN_ONLY');--> statement-breakpoint
CREATE TYPE "public"."ProfileClaimStatus" AS ENUM('PENDING', 'CLAIMED', 'SKIPPED', 'NA');--> statement-breakpoint
CREATE TYPE "public"."RelationshipType" AS ENUM('PARENT', 'CHILD', 'SPOUSE', 'SIBLING', 'PARENT_IN_LAW', 'CHILD_IN_LAW', 'SIBLING_IN_LAW', 'STEP_PARENT', 'STEP_CHILD', 'STEP_SIBLING');--> statement-breakpoint
CREATE TYPE "public"."StorageProvider" AS ENUM('LOCAL', 'S3', 'R2', 'B2');--> statement-breakpoint
CREATE TYPE "public"."SuggestionStatus" AS ENUM('PENDING', 'APPROVED', 'REJECTED');--> statement-breakpoint
CREATE TYPE "public"."SuggestionType" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'ADD_RELATIONSHIP');--> statement-breakpoint
CREATE TYPE "public"."UserRole" AS ENUM('ADMIN', 'MEMBER', 'VIEWER');--> statement-breakpoint
CREATE TABLE "Account" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"idToken" text,
	"password" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "Account_providerId_accountId_unique" UNIQUE("providerId","accountId")
);
--> statement-breakpoint
CREATE TABLE "Session" (
	"id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"userId" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "Session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "Relationship" (
	"id" text PRIMARY KEY NOT NULL,
	"personId" text NOT NULL,
	"relatedPersonId" text NOT NULL,
	"type" "RelationshipType" NOT NULL,
	"marriageDate" date,
	"divorceDate" date,
	"isActive" boolean DEFAULT true NOT NULL,
	"isAutoGenerated" boolean DEFAULT false NOT NULL,
	"sourceRelationshipId" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "Relationship_personId_relatedPersonId_type_unique" UNIQUE("type","relatedPersonId","personId")
);
--> statement-breakpoint
CREATE TABLE "Person" (
	"id" text PRIMARY KEY NOT NULL,
	"firstName" text NOT NULL,
	"lastName" text NOT NULL,
	"maidenName" text,
	"dateOfBirth" date,
	"dateOfPassing" date,
	"birthPlace" text,
	"nativePlace" text,
	"gender" "Gender",
	"photoUrl" text,
	"bio" text,
	"email" text,
	"phone" text,
	"currentAddress" jsonb,
	"workAddress" jsonb,
	"profession" text,
	"employer" text,
	"socialLinks" jsonb,
	"isLiving" boolean DEFAULT true NOT NULL,
	"deletedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"createdById" text
);
--> statement-breakpoint
CREATE TABLE "User" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"image" text,
	"passwordHash" text,
	"personId" text,
	"role" "UserRole" DEFAULT 'VIEWER' NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"mustChangePassword" boolean DEFAULT false NOT NULL,
	"preferredLanguage" text DEFAULT 'en',
	"oidcProvider" text,
	"oidcSubject" text,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"profileClaimStatus" "ProfileClaimStatus" DEFAULT 'PENDING' NOT NULL,
	"profileClaimedAt" timestamp,
	"invitedById" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"lastLoginAt" timestamp,
	"failedLoginAttempts" integer DEFAULT 0 NOT NULL,
	"lockedUntil" timestamp,
	"lastFailedLoginAt" timestamp,
	"emailNotificationPreferences" jsonb DEFAULT '{"newMemberJoined":true,"birthdayReminders":true,"suggestionsCreated":true,"suggestionsUpdated":true}'::jsonb,
	CONSTRAINT "User_email_unique" UNIQUE("email"),
	CONSTRAINT "User_personId_unique" UNIQUE("personId"),
	CONSTRAINT "User_oidcProvider_oidcSubject_unique" UNIQUE("oidcSubject","oidcProvider")
);
--> statement-breakpoint
CREATE TABLE "Verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "CalendarToken" (
	"id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"userId" text NOT NULL,
	"name" text,
	"expiresAt" timestamp NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"lastUsedAt" timestamp,
	"rotationPolicy" text DEFAULT 'annual' NOT NULL,
	"rotatedAt" timestamp,
	"rotatedFrom" text,
	"scopes" text[] DEFAULT '{"calendar:read"}',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "CalendarToken_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "OAuthState" (
	"id" text PRIMARY KEY NOT NULL,
	"state" text NOT NULL,
	"codeVerifier" text NOT NULL,
	"provider" text NOT NULL,
	"redirectTo" text,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "OAuthState_state_unique" UNIQUE("state")
);
--> statement-breakpoint
CREATE TABLE "EventMedia" (
	"id" text PRIMARY KEY NOT NULL,
	"mediaId" text NOT NULL,
	"personId" text NOT NULL,
	"eventType" text NOT NULL,
	CONSTRAINT "EventMedia_mediaId_personId_eventType_unique" UNIQUE("personId","mediaId","eventType")
);
--> statement-breakpoint
CREATE TABLE "EventParticipant" (
	"id" text PRIMARY KEY NOT NULL,
	"eventId" text NOT NULL,
	"personId" text NOT NULL,
	"role" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "EventParticipant_eventId_personId_unique" UNIQUE("personId","eventId")
);
--> statement-breakpoint
CREATE TABLE "EventSource" (
	"id" text PRIMARY KEY NOT NULL,
	"sourceId" text NOT NULL,
	"personId" text NOT NULL,
	"eventType" text NOT NULL,
	"confidence" text,
	"sourceNotes" text,
	CONSTRAINT "EventSource_sourceId_personId_eventType_unique" UNIQUE("sourceId","personId","eventType")
);
--> statement-breakpoint
CREATE TABLE "Event" (
	"id" text PRIMARY KEY NOT NULL,
	"personId" text NOT NULL,
	"type" "EventType" NOT NULL,
	"date" date,
	"place" text,
	"placeId" text,
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PlacePersonLink" (
	"id" text PRIMARY KEY NOT NULL,
	"personId" text NOT NULL,
	"placeId" text NOT NULL,
	"fromYear" integer,
	"toYear" integer,
	"type" "PersonPlaceType",
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "PlacePersonLink_personId_placeId_type_unique" UNIQUE("type","placeId","personId")
);
--> statement-breakpoint
CREATE TABLE "Place" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"placeType" "PlaceType" NOT NULL,
	"latitude" double precision,
	"longitude" double precision,
	"parentId" text,
	"description" text,
	"alternativeNames" jsonb,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "MediaObject" (
	"id" text PRIMARY KEY NOT NULL,
	"filePath" text NOT NULL,
	"format" text NOT NULL,
	"mimeType" text NOT NULL,
	"fileSize" integer NOT NULL,
	"title" text,
	"description" text,
	"source" text,
	"width" integer,
	"height" integer,
	"thumbnailPath" text,
	"webpPath" text,
	"thumb400Path" text,
	"thumb800Path" text,
	"thumb1200Path" text,
	"uploadedAt" timestamp DEFAULT now() NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PersonMedia" (
	"id" text PRIMARY KEY NOT NULL,
	"personId" text NOT NULL,
	"mediaId" text NOT NULL,
	"isPrimary" boolean DEFAULT false NOT NULL,
	"caption" text,
	"displayOrder" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "PersonMedia_personId_mediaId_unique" UNIQUE("personId","mediaId")
);
--> statement-breakpoint
CREATE TABLE "BackupSettings" (
	"id" text PRIMARY KEY NOT NULL,
	"dailyEnabled" boolean DEFAULT true NOT NULL,
	"dailyTime" text DEFAULT '02:00' NOT NULL,
	"weeklyEnabled" boolean DEFAULT true NOT NULL,
	"weeklyDay" integer DEFAULT 0 NOT NULL,
	"weeklyTime" text DEFAULT '03:00' NOT NULL,
	"monthlyEnabled" boolean DEFAULT true NOT NULL,
	"monthlyDay" integer DEFAULT 1 NOT NULL,
	"monthlyTime" text DEFAULT '04:00' NOT NULL,
	"dailyRetention" integer DEFAULT 7 NOT NULL,
	"weeklyRetention" integer DEFAULT 4 NOT NULL,
	"monthlyRetention" integer DEFAULT 12 NOT NULL,
	"storageProvider" "StorageProvider" DEFAULT 'LOCAL' NOT NULL,
	"storageBucket" text,
	"storageRegion" text,
	"storagePath" text DEFAULT 'backups' NOT NULL,
	"includePhotos" boolean DEFAULT true NOT NULL,
	"includeAuditLogs" boolean DEFAULT false NOT NULL,
	"compressLevel" integer DEFAULT 6 NOT NULL,
	"notifyOnSuccess" boolean DEFAULT false NOT NULL,
	"notifyOnFailure" boolean DEFAULT true NOT NULL,
	"notificationEmails" jsonb,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Backup" (
	"id" text PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"type" "BackupType" NOT NULL,
	"status" "BackupStatus" DEFAULT 'PENDING' NOT NULL,
	"size" bigint,
	"location" "StorageProvider" DEFAULT 'LOCAL' NOT NULL,
	"personCount" integer,
	"relationshipCount" integer,
	"eventCount" integer,
	"mediaCount" integer,
	"duration" integer,
	"error" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "AuditLog" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"action" "AuditAction" NOT NULL,
	"entityType" text NOT NULL,
	"entityId" text,
	"previousData" jsonb,
	"newData" jsonb,
	"ipAddress" text,
	"userAgent" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "EmailLog" (
	"id" text PRIMARY KEY NOT NULL,
	"recipientEmail" text NOT NULL,
	"subject" text NOT NULL,
	"emailType" text NOT NULL,
	"status" text DEFAULT 'sent' NOT NULL,
	"sentAt" timestamp DEFAULT now() NOT NULL,
	"error" text,
	"resendId" text,
	"metadata" jsonb,
	"createdById" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FamilySettings" (
	"id" text PRIMARY KEY NOT NULL,
	"familyName" text DEFAULT 'Our Family' NOT NULL,
	"description" text,
	"locale" text DEFAULT 'en' NOT NULL,
	"customLabels" jsonb,
	"defaultPrivacy" "PrivacyLevel" DEFAULT 'MEMBERS_ONLY' NOT NULL,
	"allowSelfRegistration" boolean DEFAULT true NOT NULL,
	"requireApprovalForEdits" boolean DEFAULT true NOT NULL,
	"metricsDashboardUrl" text,
	"metricsApiUrl" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Invite" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"personId" text,
	"role" "UserRole" DEFAULT 'MEMBER' NOT NULL,
	"invitedById" text NOT NULL,
	"token" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"acceptedAt" timestamp,
	"status" "InviteStatus" DEFAULT 'PENDING' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "Invite_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "ResearchNote" (
	"id" text PRIMARY KEY NOT NULL,
	"sourceId" text NOT NULL,
	"personId" text NOT NULL,
	"eventType" text NOT NULL,
	"findings" text NOT NULL,
	"methodology" text,
	"limitations" text,
	"relatedSources" text,
	"conclusionReliability" text,
	"createdById" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Source" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"author" text,
	"publicationDate" text,
	"description" text,
	"repository" text,
	"notes" text,
	"sourceType" text,
	"citationFormat" text,
	"doi" text,
	"url" text,
	"isbn" text,
	"callNumber" text,
	"accessDate" timestamp,
	"confidence" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Suggestion" (
	"id" text PRIMARY KEY NOT NULL,
	"type" "SuggestionType" NOT NULL,
	"targetPersonId" text,
	"suggestedData" jsonb NOT NULL,
	"reason" text,
	"status" "SuggestionStatus" DEFAULT 'PENDING' NOT NULL,
	"submittedById" text NOT NULL,
	"reviewedById" text,
	"reviewNote" text,
	"submittedAt" timestamp DEFAULT now() NOT NULL,
	"reviewedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "DashboardPreferences" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"layout" jsonb DEFAULT '{"widgets":[]}'::jsonb NOT NULL,
	"widgets" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "DashboardPreferences_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "DeviceToken" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"token" varchar(512) NOT NULL,
	"platform" varchar(20) NOT NULL,
	"deviceId" varchar(255),
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Notification" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"type" varchar(50) NOT NULL,
	"title" varchar(255) NOT NULL,
	"body" varchar(1024) NOT NULL,
	"data" jsonb,
	"readAt" timestamp,
	"sentAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_account_userId" ON "Account" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_session_expiresAt" ON "Session" USING btree ("expiresAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_session_userId" ON "Session" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_isAutoGenerated" ON "Relationship" USING btree ("isAutoGenerated" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_personId" ON "Relationship" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_personId_type" ON "Relationship" USING btree ("personId" text_ops,"type" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_relatedPersonId" ON "Relationship" USING btree ("relatedPersonId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_relatedPersonId_type" ON "Relationship" USING btree ("relatedPersonId" text_ops,"type" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_relationship_sourceRelationshipId" ON "Relationship" USING btree ("sourceRelationshipId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_person_createdById" ON "Person" USING btree ("createdById" text_ops);--> statement-breakpoint
CREATE INDEX "idx_person_dateOfBirth" ON "Person" USING btree ("dateOfBirth" date_ops);--> statement-breakpoint
CREATE INDEX "idx_person_isLiving" ON "Person" USING btree ("isLiving" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_person_deletedAt" ON "Person" USING btree ("deletedAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_person_lastName_firstName" ON "Person" USING btree ("lastName" text_ops,"firstName" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_email" ON "User" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_oidcProvider" ON "User" USING btree ("oidcProvider" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_personId" ON "User" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_verification_identifier" ON "Verification" USING btree ("identifier" text_ops);--> statement-breakpoint
CREATE INDEX "idx_calendarToken_expiresAt" ON "CalendarToken" USING btree ("expiresAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_calendarToken_isActive" ON "CalendarToken" USING btree ("isActive" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_calendarToken_token" ON "CalendarToken" USING btree ("token" text_ops);--> statement-breakpoint
CREATE INDEX "idx_calendarToken_userId" ON "CalendarToken" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_calendarToken_userId_isActive" ON "CalendarToken" USING btree ("userId" text_ops,"isActive" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_oAuthState_expiresAt" ON "OAuthState" USING btree ("expiresAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_oAuthState_state" ON "OAuthState" USING btree ("state" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventMedia_eventType" ON "EventMedia" USING btree ("eventType" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventMedia_mediaId" ON "EventMedia" USING btree ("mediaId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventMedia_personId" ON "EventMedia" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventParticipant_eventId" ON "EventParticipant" USING btree ("eventId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventParticipant_personId" ON "EventParticipant" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventSource_eventType" ON "EventSource" USING btree ("eventType" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventSource_personId" ON "EventSource" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_eventSource_sourceId" ON "EventSource" USING btree ("sourceId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_event_date" ON "Event" USING btree ("date" date_ops);--> statement-breakpoint
CREATE INDEX "idx_event_personId" ON "Event" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_event_placeId" ON "Event" USING btree ("placeId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_event_type" ON "Event" USING btree ("type" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_placePersonLink_personId" ON "PlacePersonLink" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_placePersonLink_placeId" ON "PlacePersonLink" USING btree ("placeId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_place_latitude_longitude" ON "Place" USING btree ("latitude" float8_ops,"longitude" float8_ops);--> statement-breakpoint
CREATE INDEX "idx_place_name" ON "Place" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_place_parentId" ON "Place" USING btree ("parentId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_place_placeType" ON "Place" USING btree ("placeType" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_mediaObject_filePath" ON "MediaObject" USING btree ("filePath" text_ops);--> statement-breakpoint
CREATE INDEX "idx_mediaObject_uploadedAt" ON "MediaObject" USING btree ("uploadedAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_personMedia_isPrimary" ON "PersonMedia" USING btree ("isPrimary" bool_ops);--> statement-breakpoint
CREATE INDEX "idx_personMedia_mediaId" ON "PersonMedia" USING btree ("mediaId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_personMedia_personId" ON "PersonMedia" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_backup_createdAt" ON "Backup" USING btree ("createdAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_backup_status" ON "Backup" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_backup_type_createdAt" ON "Backup" USING btree ("type" enum_ops,"createdAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_auditLog_createdAt" ON "AuditLog" USING btree ("createdAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_auditLog_entityType_entityId" ON "AuditLog" USING btree ("entityType" text_ops,"entityId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_auditLog_userId" ON "AuditLog" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_emailLog_emailType" ON "EmailLog" USING btree ("emailType" text_ops);--> statement-breakpoint
CREATE INDEX "idx_emailLog_recipientEmail" ON "EmailLog" USING btree ("recipientEmail" text_ops);--> statement-breakpoint
CREATE INDEX "idx_emailLog_sentAt" ON "EmailLog" USING btree ("sentAt" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_emailLog_status" ON "EmailLog" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_invite_email" ON "Invite" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "idx_invite_invitedById" ON "Invite" USING btree ("invitedById" text_ops);--> statement-breakpoint
CREATE INDEX "idx_invite_status" ON "Invite" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_researchNote_createdById" ON "ResearchNote" USING btree ("createdById" text_ops);--> statement-breakpoint
CREATE INDEX "idx_researchNote_eventType" ON "ResearchNote" USING btree ("eventType" text_ops);--> statement-breakpoint
CREATE INDEX "idx_researchNote_personId" ON "ResearchNote" USING btree ("personId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_researchNote_sourceId" ON "ResearchNote" USING btree ("sourceId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_source_doi" ON "Source" USING btree ("doi" text_ops);--> statement-breakpoint
CREATE INDEX "idx_source_sourceType" ON "Source" USING btree ("sourceType" text_ops);--> statement-breakpoint
CREATE INDEX "idx_source_title" ON "Source" USING btree ("title" text_ops);--> statement-breakpoint
CREATE INDEX "idx_suggestion_status" ON "Suggestion" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_suggestion_submittedById" ON "Suggestion" USING btree ("submittedById" text_ops);--> statement-breakpoint
CREATE INDEX "idx_suggestion_targetPersonId" ON "Suggestion" USING btree ("targetPersonId" text_ops);--> statement-breakpoint
CREATE INDEX "idx_dashboardPreferences_userId" ON "DashboardPreferences" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_deviceToken_userId" ON "DeviceToken" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_deviceToken_isActive" ON "DeviceToken" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "idx_deviceToken_userId_isActive" ON "DeviceToken" USING btree ("userId","isActive");--> statement-breakpoint
CREATE INDEX "idx_deviceToken_deviceId" ON "DeviceToken" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "idx_notification_userId" ON "Notification" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "idx_notification_type" ON "Notification" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_notification_createdAt" ON "Notification" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "idx_notification_userId_readAt" ON "Notification" USING btree ("userId","readAt");--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE INDEX person_fts_idx ON "Person" USING gin(
  (
    setweight(to_tsvector('english', COALESCE("firstName", '')), 'A') ||
    setweight(to_tsvector('english', COALESCE("lastName", '')), 'A') ||
    setweight(to_tsvector('english', COALESCE("maidenName", '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(bio, '')), 'C') ||
    setweight(to_tsvector('english', COALESCE("birthPlace", '')), 'D') ||
    setweight(to_tsvector('english', COALESCE("nativePlace", '')), 'D') ||
    setweight(to_tsvector('english', COALESCE(profession, '')), 'D')
  )
);--> statement-breakpoint
CREATE INDEX person_trgm_firstname_idx ON "Person" USING gin("firstName" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX person_trgm_lastname_idx ON "Person" USING gin("lastName" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX person_trgm_maidenname_idx ON "Person" USING gin("maidenName" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX person_trgm_birthplace_idx ON "Person" USING gin("birthPlace" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX person_trgm_profession_idx ON "Person" USING gin(profession gin_trgm_ops);
