import type { PersonSummary, RelationshipSummary } from "./types";

export const PEOPLE_FIXTURE: Array<PersonSummary> = [
  {
    id: "p-001",
    firstName: "Hari",
    lastName: "Sharma",
    relation: "Great-Great-Grandfather",
    birthYear: 1905,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-002",
    firstName: "Savitri",
    lastName: "Sharma",
    relation: "Great-Great-Grandmother",
    birthYear: 1910,
    city: "Jodhpur, Rajasthan",
  },
  {
    id: "p-003",
    firstName: "Ratan",
    lastName: "Patel",
    relation: "Great-Great-Grandfather",
    birthYear: 1908,
    city: "Ahmedabad, Gujarat",
  },
  {
    id: "p-004",
    firstName: "Kusuma",
    lastName: "Patel",
    relation: "Great-Great-Grandmother",
    birthYear: 1912,
    city: "Surat, Gujarat",
  },
  {
    id: "p-005",
    firstName: "Rajendra",
    lastName: "Sharma",
    relation: "Great-Grandfather",
    birthYear: 1935,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-006",
    firstName: "Kamla",
    lastName: "Sharma",
    relation: "Great-Grandmother",
    birthYear: 1940,
    city: "Agra, Uttar Pradesh",
  },
  {
    id: "p-007",
    firstName: "Mohan",
    lastName: "Patel",
    relation: "Great-Grandfather",
    birthYear: 1938,
    city: "Ahmedabad, Gujarat",
  },
  {
    id: "p-008",
    firstName: "Lakshmi",
    lastName: "Patel",
    relation: "Great-Grandmother",
    birthYear: 1942,
    city: "Surat, Gujarat",
  },
  {
    id: "p-009",
    firstName: "Vikram",
    lastName: "Sharma",
    relation: "Grandfather",
    birthYear: 1960,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-010",
    firstName: "Priya",
    lastName: "Sharma",
    relation: "Grandmother",
    birthYear: 1963,
    city: "Ahmedabad, Gujarat",
  },
  {
    id: "p-011",
    firstName: "Ajay",
    lastName: "Sharma",
    relation: "Grand-uncle",
    birthYear: 1965,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-012",
    firstName: "Sunita",
    lastName: "Sharma",
    relation: "Grand-aunt",
    birthYear: 1968,
    city: "Delhi",
  },
  {
    id: "p-013",
    firstName: "Sanjay",
    lastName: "Patel",
    relation: "Grand-uncle",
    birthYear: 1962,
    city: "Ahmedabad, Gujarat",
  },
  {
    id: "p-014",
    firstName: "Rekha",
    lastName: "Patel",
    relation: "Grand-aunt",
    birthYear: 1966,
    city: "Mumbai, Maharashtra",
  },
  {
    id: "p-015",
    firstName: "Arjun",
    lastName: "Sharma",
    relation: "Parent",
    birthYear: 1988,
    city: "Bangalore, Karnataka",
  },
  {
    id: "p-016",
    firstName: "Neha",
    lastName: "Sharma",
    relation: "Parent",
    birthYear: 1990,
    city: "Delhi",
  },
  {
    id: "p-017",
    firstName: "Meera",
    lastName: "Verma",
    relation: "Parent",
    birthYear: 1991,
    city: "Bangalore, Karnataka",
  },
  {
    id: "p-018",
    firstName: "Rohan",
    lastName: "Verma",
    relation: "Parent",
    birthYear: 1989,
    city: "Chennai, Tamil Nadu",
  },
  {
    id: "p-019",
    firstName: "Rahul",
    lastName: "Sharma",
    relation: "Parent",
    birthYear: 1992,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-020",
    firstName: "Ananya",
    lastName: "Sharma",
    relation: "Parent",
    birthYear: 1994,
    city: "Lucknow, Uttar Pradesh",
  },
  {
    id: "p-021",
    firstName: "Aditya",
    lastName: "Patel",
    relation: "Parent",
    birthYear: 1990,
    city: "Ahmedabad, Gujarat",
  },
  {
    id: "p-022",
    firstName: "Kavya",
    lastName: "Patel",
    relation: "Parent",
    birthYear: 1992,
    city: "Hyderabad, Telangana",
  },
  {
    id: "p-023",
    firstName: "Aarav",
    lastName: "Sharma",
    relation: "Child",
    birthYear: 2015,
    city: "Bangalore, Karnataka",
  },
  {
    id: "p-024",
    firstName: "Isha",
    lastName: "Sharma",
    relation: "Child",
    birthYear: 2018,
    city: "Bangalore, Karnataka",
  },
  {
    id: "p-025",
    firstName: "Vihaan",
    lastName: "Verma",
    relation: "Child",
    birthYear: 2016,
    city: "Delhi",
  },
  {
    id: "p-026",
    firstName: "Sara",
    lastName: "Verma",
    relation: "Child",
    birthYear: 2019,
    city: "Delhi",
  },
  {
    id: "p-027",
    firstName: "Kabir",
    lastName: "Sharma",
    relation: "Child",
    birthYear: 2017,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-028",
    firstName: "Riya",
    lastName: "Sharma",
    relation: "Child",
    birthYear: 2020,
    city: "Jaipur, Rajasthan",
  },
  {
    id: "p-029",
    firstName: "Aryan",
    lastName: "Patel",
    relation: "Child",
    birthYear: 2018,
    city: "Mumbai, Maharashtra",
  },
  {
    id: "p-030",
    firstName: "Mira",
    lastName: "Patel",
    relation: "Child",
    birthYear: 2021,
    city: "Mumbai, Maharashtra",
  },
];

export const RELATIONSHIP_FIXTURE: Array<RelationshipSummary> = [
  { id: "r-001", personId: "p-001", relatedPersonId: "p-002", type: "SPOUSE" },
  { id: "r-002", personId: "p-002", relatedPersonId: "p-001", type: "SPOUSE" },
  { id: "r-003", personId: "p-003", relatedPersonId: "p-004", type: "SPOUSE" },
  { id: "r-004", personId: "p-004", relatedPersonId: "p-003", type: "SPOUSE" },
  { id: "r-005", personId: "p-005", relatedPersonId: "p-006", type: "SPOUSE" },
  { id: "r-006", personId: "p-006", relatedPersonId: "p-005", type: "SPOUSE" },
  { id: "r-007", personId: "p-007", relatedPersonId: "p-008", type: "SPOUSE" },
  { id: "r-008", personId: "p-008", relatedPersonId: "p-007", type: "SPOUSE" },
  { id: "r-009", personId: "p-009", relatedPersonId: "p-010", type: "SPOUSE" },
  { id: "r-010", personId: "p-010", relatedPersonId: "p-009", type: "SPOUSE" },
  { id: "r-011", personId: "p-011", relatedPersonId: "p-012", type: "SPOUSE" },
  { id: "r-012", personId: "p-012", relatedPersonId: "p-011", type: "SPOUSE" },
  { id: "r-013", personId: "p-013", relatedPersonId: "p-014", type: "SPOUSE" },
  { id: "r-014", personId: "p-014", relatedPersonId: "p-013", type: "SPOUSE" },
  { id: "r-015", personId: "p-015", relatedPersonId: "p-016", type: "SPOUSE" },
  { id: "r-016", personId: "p-016", relatedPersonId: "p-015", type: "SPOUSE" },
  { id: "r-017", personId: "p-017", relatedPersonId: "p-018", type: "SPOUSE" },
  { id: "r-018", personId: "p-018", relatedPersonId: "p-017", type: "SPOUSE" },
  { id: "r-019", personId: "p-019", relatedPersonId: "p-020", type: "SPOUSE" },
  { id: "r-020", personId: "p-020", relatedPersonId: "p-019", type: "SPOUSE" },
  { id: "r-021", personId: "p-021", relatedPersonId: "p-022", type: "SPOUSE" },
  { id: "r-022", personId: "p-022", relatedPersonId: "p-021", type: "SPOUSE" },

  { id: "r-023", personId: "p-005", relatedPersonId: "p-001", type: "PARENT" },
  { id: "r-024", personId: "p-001", relatedPersonId: "p-005", type: "CHILD" },
  { id: "r-025", personId: "p-005", relatedPersonId: "p-002", type: "PARENT" },
  { id: "r-026", personId: "p-002", relatedPersonId: "p-005", type: "CHILD" },
  { id: "r-027", personId: "p-007", relatedPersonId: "p-003", type: "PARENT" },
  { id: "r-028", personId: "p-003", relatedPersonId: "p-007", type: "CHILD" },
  { id: "r-029", personId: "p-007", relatedPersonId: "p-004", type: "PARENT" },
  { id: "r-030", personId: "p-004", relatedPersonId: "p-007", type: "CHILD" },

  { id: "r-031", personId: "p-009", relatedPersonId: "p-005", type: "PARENT" },
  { id: "r-032", personId: "p-005", relatedPersonId: "p-009", type: "CHILD" },
  { id: "r-033", personId: "p-009", relatedPersonId: "p-006", type: "PARENT" },
  { id: "r-034", personId: "p-006", relatedPersonId: "p-009", type: "CHILD" },
  { id: "r-035", personId: "p-011", relatedPersonId: "p-005", type: "PARENT" },
  { id: "r-036", personId: "p-005", relatedPersonId: "p-011", type: "CHILD" },
  { id: "r-037", personId: "p-011", relatedPersonId: "p-006", type: "PARENT" },
  { id: "r-038", personId: "p-006", relatedPersonId: "p-011", type: "CHILD" },
  { id: "r-039", personId: "p-010", relatedPersonId: "p-007", type: "PARENT" },
  { id: "r-040", personId: "p-007", relatedPersonId: "p-010", type: "CHILD" },
  { id: "r-041", personId: "p-010", relatedPersonId: "p-008", type: "PARENT" },
  { id: "r-042", personId: "p-008", relatedPersonId: "p-010", type: "CHILD" },
  { id: "r-043", personId: "p-013", relatedPersonId: "p-007", type: "PARENT" },
  { id: "r-044", personId: "p-007", relatedPersonId: "p-013", type: "CHILD" },
  { id: "r-045", personId: "p-013", relatedPersonId: "p-008", type: "PARENT" },
  { id: "r-046", personId: "p-008", relatedPersonId: "p-013", type: "CHILD" },

  { id: "r-047", personId: "p-017", relatedPersonId: "p-009", type: "PARENT" },
  { id: "r-048", personId: "p-009", relatedPersonId: "p-017", type: "CHILD" },
  { id: "r-049", personId: "p-017", relatedPersonId: "p-010", type: "PARENT" },
  { id: "r-050", personId: "p-010", relatedPersonId: "p-017", type: "CHILD" },
  { id: "r-051", personId: "p-019", relatedPersonId: "p-011", type: "PARENT" },
  { id: "r-052", personId: "p-011", relatedPersonId: "p-019", type: "CHILD" },
  { id: "r-053", personId: "p-019", relatedPersonId: "p-012", type: "PARENT" },
  { id: "r-054", personId: "p-012", relatedPersonId: "p-019", type: "CHILD" },
  { id: "r-055", personId: "p-021", relatedPersonId: "p-013", type: "PARENT" },
  { id: "r-056", personId: "p-013", relatedPersonId: "p-021", type: "CHILD" },
  { id: "r-057", personId: "p-021", relatedPersonId: "p-014", type: "PARENT" },
  { id: "r-058", personId: "p-014", relatedPersonId: "p-021", type: "CHILD" },

  { id: "r-059", personId: "p-023", relatedPersonId: "p-015", type: "PARENT" },
  { id: "r-060", personId: "p-015", relatedPersonId: "p-023", type: "CHILD" },
  { id: "r-061", personId: "p-023", relatedPersonId: "p-016", type: "PARENT" },
  { id: "r-062", personId: "p-016", relatedPersonId: "p-023", type: "CHILD" },
  { id: "r-063", personId: "p-024", relatedPersonId: "p-015", type: "PARENT" },
  { id: "r-064", personId: "p-015", relatedPersonId: "p-024", type: "CHILD" },
  { id: "r-065", personId: "p-024", relatedPersonId: "p-016", type: "PARENT" },
  { id: "r-066", personId: "p-016", relatedPersonId: "p-024", type: "CHILD" },
  { id: "r-067", personId: "p-025", relatedPersonId: "p-017", type: "PARENT" },
  { id: "r-068", personId: "p-017", relatedPersonId: "p-025", type: "CHILD" },
  { id: "r-069", personId: "p-025", relatedPersonId: "p-018", type: "PARENT" },
  { id: "r-070", personId: "p-018", relatedPersonId: "p-025", type: "CHILD" },
  { id: "r-071", personId: "p-026", relatedPersonId: "p-017", type: "PARENT" },
  { id: "r-072", personId: "p-017", relatedPersonId: "p-026", type: "CHILD" },
  { id: "r-073", personId: "p-026", relatedPersonId: "p-018", type: "PARENT" },
  { id: "r-074", personId: "p-018", relatedPersonId: "p-026", type: "CHILD" },
  { id: "r-075", personId: "p-027", relatedPersonId: "p-019", type: "PARENT" },
  { id: "r-076", personId: "p-019", relatedPersonId: "p-027", type: "CHILD" },
  { id: "r-077", personId: "p-027", relatedPersonId: "p-020", type: "PARENT" },
  { id: "r-078", personId: "p-020", relatedPersonId: "p-027", type: "CHILD" },
  { id: "r-079", personId: "p-028", relatedPersonId: "p-019", type: "PARENT" },
  { id: "r-080", personId: "p-019", relatedPersonId: "p-028", type: "CHILD" },
  { id: "r-081", personId: "p-028", relatedPersonId: "p-020", type: "PARENT" },
  { id: "r-082", personId: "p-020", relatedPersonId: "p-028", type: "CHILD" },
  { id: "r-083", personId: "p-029", relatedPersonId: "p-021", type: "PARENT" },
  { id: "r-084", personId: "p-021", relatedPersonId: "p-029", type: "CHILD" },
  { id: "r-085", personId: "p-029", relatedPersonId: "p-022", type: "PARENT" },
  { id: "r-086", personId: "p-022", relatedPersonId: "p-029", type: "CHILD" },
  { id: "r-087", personId: "p-030", relatedPersonId: "p-021", type: "PARENT" },
  { id: "r-088", personId: "p-021", relatedPersonId: "p-030", type: "CHILD" },
  { id: "r-089", personId: "p-030", relatedPersonId: "p-022", type: "PARENT" },
  { id: "r-090", personId: "p-022", relatedPersonId: "p-030", type: "CHILD" },

  { id: "r-091", personId: "p-009", relatedPersonId: "p-011", type: "SIBLING" },
  { id: "r-092", personId: "p-011", relatedPersonId: "p-009", type: "SIBLING" },
  { id: "r-093", personId: "p-010", relatedPersonId: "p-013", type: "SIBLING" },
  { id: "r-094", personId: "p-013", relatedPersonId: "p-010", type: "SIBLING" },
  { id: "r-095", personId: "p-017", relatedPersonId: "p-019", type: "SIBLING" },
  { id: "r-096", personId: "p-019", relatedPersonId: "p-017", type: "SIBLING" },
  { id: "r-097", personId: "p-023", relatedPersonId: "p-024", type: "SIBLING" },
  { id: "r-098", personId: "p-024", relatedPersonId: "p-023", type: "SIBLING" },
  { id: "r-099", personId: "p-025", relatedPersonId: "p-026", type: "SIBLING" },
  { id: "r-100", personId: "p-026", relatedPersonId: "p-025", type: "SIBLING" },
  { id: "r-101", personId: "p-027", relatedPersonId: "p-028", type: "SIBLING" },
  { id: "r-102", personId: "p-028", relatedPersonId: "p-027", type: "SIBLING" },
  { id: "r-103", personId: "p-029", relatedPersonId: "p-030", type: "SIBLING" },
  { id: "r-104", personId: "p-030", relatedPersonId: "p-029", type: "SIBLING" },
];
